version: "3"
services:
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
    - "8080:8080"
    volumes:
    - .:/usr/src/app/:rw
    - /usr/src/app/node_modules
    environment:
    - NODE_ENV=prod
    command: npm run build:prod